# Generated by Django 3.2 on 2022-10-25 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('idVr', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tarea',
            name='min_exercise_version',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='ejercicio',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.ejercicio'),
        ),
    ]
