# Generated by Django 3.2 on 2022-09-21 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0002_auto_20220920_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='centro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vroom.centro'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_centro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.centro'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.curso'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vroom.ejercicio'),
        ),
    ]
