# Generated by Django 3.2 on 2022-09-26 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0004_alter_usuario_curso_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
