# Generated by Django 3.2 on 2022-09-29 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0005_alter_tarea_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pin',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
